# Generated by Django 4.2.13 on 2026-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_resume_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
