stages:
  - test

default:
  image: python:3.13-slim

services:
  - name: postgres:16
    alias: postgres

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  POSTGRES_DB: applyflow_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/applyflow_test"

  SECRET_KEY: "gitlab-ci-only-secret-key"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1"

cache:
  key:
    files:
      - requirements.txt
  paths:
    - .cache/pip

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

django_checks:
  stage: test

  script:
    - python manage.py check
    - python manage.py makemigrations --check --dry-run
    - python manage.py migrate --noinput
    - python manage.py test

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'